### ISSUE TITLE
Unregister method & Test if method is registered

### ISSUE THREAD

**Issue by micodeyt** [Muirey03/MRYIPC#1]
Hello !

I have a few questions : 
- is it possible to unregister a method, registered with addTarget method ?
- is it possible to test if a method was registered from it's name ?

**Comment by Muirey03** [comment]
Addressed in commit 88dfd62f66db126f356fc0888a2c9d9202904913. Methods can be removed with `removeMethodForSelector:` and a method list can be accessed with the `selectors` property.

An example of being able to test if a method is registered would be:
```
if ([center.selectors containsObject:@"aSelector:"])
    // method is registered
else
    // method is not registered
```

**Comment by micodeyt** [comment]
To clarify the second point, I wanted to know if it was possible to test if a method was registered in an other process, by an other instance of MRYIPCCenter.

**Comment by Muirey03** [comment]
@micodeyt You can implement that on your end. Just create a method on the server that takes in a method name and returns a boolean to indicate whether it is implemented or not.
