### ISSUE TITLE
Fails to create MRYIPCCenter on iOS 14

### ISSUE THREAD

**Issue by iandwelker** [Muirey03/MRYIPC#11]
When trying to create an MRYIPCCenter on iOS 14, it fails. When watching the syslog, an error shows which reads `Sandbox: TweakName(940) deny(1) mach-register mry:CenterName-service`. Then, when trying to call a method in said center, it throws `*** Terminating app due to uncaught exception 'MRYIPCException', reason: 'callExternalMethod:withArguments:completion: - Failed to lookup service port: Unknown service name'`. 

I completely understand that the jailbreak was just released and it may take some time for you to update; I just wanted to provide information that may help fix the issue. Let me know if there's any other way I can help.

**Comment by Muirey03** [comment]
Please show me the code that you were using.

**Comment by iandwelker** [comment]
```objective-c
@interface LaunchSMSIPC : NSObject
@end

@implementation LaunchSMSIPC {
	MRYIPCCenter* _center;
}

+ (instancetype)sharedInstance {
	static dispatch_once_t onceToken = 0;
	__strong static LaunchSMSIPC* sharedInstance = nil;
	dispatch_once(&onceToken, ^{
		sharedInstance = [[self alloc] init];
	});
	return sharedInstance;
}

- (instancetype)init {
	if ((self = [super init])) {
		_center = [MRYIPCCenter centerNamed:@"com.ianwelker.smserverLaunch"];
		[_center addTarget:self action:@selector(launchSMS)];
		[_center addTarget:self action:@selector(checkIfRunning:)];
	}
	return self;
}

- (void)launchSMS {
	dispatch_async(dispatch_get_main_queue(), ^{
	    [[UIApplication sharedApplication] launchApplicationWithIdentifier:@"com.apple.MobileSMS" suspended:YES];
	});
}

- (NSString *)checkIfRunning:(NSString *)bundle_id { 
	SBApplication *app = [[%c(SBApplicationController) sharedInstance] applicationWithBundleIdentifier:bundle_id];
	return app.processState != nil ? @"YES" : @"NO";
}

@end

%ctor {
	
	NSString *bundleID = [[NSBundle mainBundle] bundleIdentifier];

	if ([bundleID isEqualToString:@"com.apple.springboard"]) {
		LaunchSMSIPC* center = [LaunchSMSIPC sharedInstance];
	}
}
```

It's a bit, I know. If you'd like to look at the full code, check `Tweak.xm` in [libsmserver](https://github.com/iandwelker/libsmserver), lines 175-EOF.

**Comment by iandwelker** [comment]
Everything has just started working; I didn't change anything, install any new dependencies, or anything like that, but it's working well now. Thanks for the quick response; I'll close this issue.
