### ISSUE TITLE
Failed to lookup service port: Unknown service name

### ISSUE THREAD

**Issue by PopsicleTreehouse** [Muirey03/MRYIPC#13]
Whenever either `callExternalMethod` or `callExternalVoidMethod` is called it crashes the current process. The full backtrace is in the attached file. This is the implementation:

```
#import <MRYIPCCenter.h>
#import <UIKit/UIKit.h>

@interface CanvasBackgroundServer : NSObject
+ (void)load;
@end

@implementation CanvasBackgroundServer
{
    MRYIPCCenter *_center;
    NSData *_data;
}

+ (void)load
{
    [self sharedInstance];
}

+ (instancetype)sharedInstance
{
    static dispatch_once_t onceToken = 0;
    __strong static CanvasBackgroundServer *sharedInstance = nil;
    dispatch_once(&onceToken, ^{
      sharedInstance = [[self alloc] init];
    });
    return sharedInstance;
}

- (instancetype)init
{
    if ((self = [super init]))
    {
        _center = [MRYIPCCenter centerNamed:@"com.popsicletreehouse.CanvasIPCServer"];
        [_center addTarget:self action:@selector(getCanvas:)];
        [_center addTarget:self action:@selector(updateCanvas:)];
    }
    return self;
}
- (NSData *)getCanvas
{
    return _data;
}
- (void)updateCanvas:(NSData *)args
{
    _data = args;
}
@end
```
This is the relevant tweak.xm code:
```
static UIView *canvasVideo;
static MRYIPCCenter *center;

%hook CSCoverSheetViewController
-(void)viewWillAppear:(BOOL)arg1 {
    %orig;
    NSData *data = [center callExternalMethod:@selector(getCanvas) withArguments:nil];
    NSLog(@"spotifycanvas after callExternalMethod");
    canvasVideo = [NSKeyedUnarchiver unarchiveObjectWithData: data];
}
%end
%hook SPTCanvasNowPlayingContentLayerCellCollectionViewCell
-(void)setCanvasView:(id)arg1 {
   %orig;
   if(arg1)
   [center callExternalVoidMethod:@selector(updateCanvas:)withArguments:[NSKeyedArchiver archivedDataWithRootObject:arg1]];
}
%end
%ctor {
	center = [MRYIPCCenter centerNamed:@"com.popsicletreehouse.CanvasIPCServer"];
}
```
[Log.txt](https://github.com/Muirey03/MRYIPC/files/6087874/Log.txt)

**Comment by Muirey03** [comment]
Please send me a full log, from Cr4shed not CrashReporter so I can see the relevant NSException information. Also please provide more information. What process is the server in? What process is calling `callExternalVoidMethod`? What process is crashing out of the two? etc.

**Comment by PopsicleTreehouse** [comment]
[SpringBoard@2021-03-05_8:43_am.log](https://github.com/Muirey03/MRYIPC/files/6094533/SpringBoard%402021-03-05_8.43_am.log)
SpringBoard is calling `callExternalVoidMethod`. Spotify is calling `callExternalMethod`. SpringBoard crashes when calling `callExternalVoidMethod` but both crash when they each access the server. I'm not quite sure which process the server's in, could you tell me how to figure that out?

**Comment by PopsicleTreehouse** [comment]
I moved the files outside of the enclosing folder, and for some reason that made my tweak stop throwing the error
