### ISSUE TITLE
SpringBoard crash in libMYRPC.dylib iOS 12.4

### ISSUE THREAD

**Issue by badger200** [Muirey03/MRYIPC#4]
Hi I tweeted you but you didn’t reply. 
iOS 12.4
iPad Pro 9.7”
Unc0ver 4.3.1

I’ve experienced at least 2 SpringBoard crashes attributed due to libMYRPC in the past 2 days. Here’s the most recent log.

Unusual conditions: my disk is nearly always full and my device is often disk-thrashing as it clears app caches etc to free space.

Attached is CrashReporter .ips log blaming libMYRPC.dylib

[text.txt](https://github.com/Muirey03/MRYIPC/files/4546316/text.txt)

**Comment by Muirey03** [comment]
Not caused my libMRYIPC. The crash occurs in `-[SBPinFloatingApplicationPanSystemGestureRecognizerWorkspaceTransaction _captureCompletionAction]` (which is totally unrelated to libmryipc) on thread 0 (`com.apple.main-thread`). The occurrence of libmryipc.dylib is in thread 12 (`com.muirey03.libmryipc-messageQueue`) and only appears in the log as the thread was blocking on a `mach_msg_trap`.
