### ISSUE TITLE
com.apple.WebKit.WebContent process crashed

### ISSUE THREAD

**Issue by ienthach** [Muirey03/MRYIPC#5]
My iphone 6s iOS 13.4.1. MRYIPC 2.0

i follow your instruction:
- server on SpringBoard
- client in com.apple.WebKit.WebContent 

com.apple.WebKit.WebContent will crash when callExternalMethod. but every process work fine. 

this is crash report
[com.apple.WebKit.WebContent-2020-05-27-010515.ips.zip]
(https://github.com/Muirey03/MRYIPC/files/4685664/com.apple.WebKit.WebContent-2020-05-27-010515.ips.zip)

**Comment by Muirey03** [comment]
Closing this now that 2.0 has been released. I'll reopen if you still experience this issue
