### ISSUE TITLE
Can I run two servers with the same name in two apps?

### ISSUE THREAD

**Issue by youngzzzzzzz** [Muirey03/MRYIPC#6]
Can I run a server in tweak of Springboard, while at the same time run a server with the same center name in a daemon??

**Comment by Muirey03** [comment]
No. Never do that. Messages can only have one endpoint, if you setup multiple servers with the same name, MRYIPC cannot possibly know the correct destination for your message, leading to undefined behaviour. There should be absolutely no reason why you would want to do this in the first place, you should have different names for the SpringBoard and Daemon servers.
