### ISSUE TITLE
Invalid reply message

### ISSUE THREAD

**Issue by youngzzzzzzz** [Muirey03/MRYIPC#8]
```
-(BOOL)_validateMessage:(MRYIPCMessage_t*)msg forID:(uint32_t)msgID
{
   if (msg->base.header.msgh_size < sizeof(*msg))
        return NO;
    if (msg->base.header.msgh_id != msgID)
        return NO;
   if (!msg->messageName.address || msg->messageName.size < 2)
        return NO;
    
    return YES;
}
```

In this method, I NSLog to see what had happened while crashing.
It crashs every time while **msg->base.header.msgh_size** is **24** and **msg->base.header.msgh_id** is **71**
What is magic number "**71**" means?

**Comment by Muirey03** [comment]
Please provided sample code to trigger the issue so that I can debug it on my device

**Comment by youngzzzzzzz** [comment]
It crashs at sometimes not always.
my project is something like that:

a tweak working in SpringBoard with a center server "CenterSB", and a client "CenterDM"
a daemon with a center server "CenterDM".
a UIApp with  a center client  "CenterSB".

in UIApp
I call [self askSBToDo:info];
```
-(void)initCenter
{
    _center = [MRYIPCCenter centerNamed:@"CenterSB"];
}
- (void)askSBToDo:(NSDictionary*)info
{
    NSDictionary *ret = [_center callExternalMethod:@selector(askSBToDo:) withArguments:info];
}
```

in SpringBoard
```
-(void)initCenter
{
    _centerSB = [MRYIPCCenter centerNamed:@"CenterSB"];
    [_centerSB addTarget:self action:@selector(askSBToDo:)];
    
    _centerDM = [MRYIPCCenter centerNamed:@"CenterDM"];
}
- (NSDictionary*)askSBToDo:(NSDictionary*)info
{
    //sb doing sth here
   //after sb finished , then ask daemon to do sth
    NSDictionary *ret = [_centerDM callExternalMethod:@selector(askDMToDo:) withArguments:info];
    return ret;
}
```


in my daemon
```
-(void)initCenter
{
    _centerDM = [MRYIPCCenter centerNamed:@"CenterDM"];
    [_centerDM addTarget:self action:@selector(askDMToDo:)];
}
- (NSDictionary*)askDMToDo:(NSDictionary*)info
{
    //damon doing sth here and MRYIPCCenter crashed sometimes
    return dic;
}
```

**Comment by youngzzzzzzz** [comment]
by the way, my device is iphone7 ios12

**Comment by Muirey03** [comment]
What version of MRYIPC are you using?

**Comment by youngzzzzzzz** [comment]
ver 2.0

**Comment by youngzzzzzzz** [comment]
Sorry, I have figured out what happened.
I did some keychain work in my daemon, and it caused memory leaked.(SecItemCopyMatching)
Then my daemon crashed and _validateMessage retrun NO with the msgh_id "71" magic number.

Sorry for bothering you ;)
